COLUMNS:
  ID: int64
  Age: int64
  Experience: int64
  Income: int64
  ZIP Code: int64
  Family: intt64
  CCAvg: float64
  Education: int64
  Mortgage: int64
  Personal Loan: int64
  Securities Account: int64
  CD Account: int64
  Online: int64
  CreditCard: int64


target_column: Personal Loan

drop_columns:
  - ID
  - ZIP Code

categorical_columns:
  - Education

numerical_columns:
  - Age
  - Experience
  - Income
  - Family
  - CCAvg
  - Mortgage
  - Securities Account
  - CD Account
  - Online
  - CreditCard